### PR TITLE
cli: test the deletion of cobs

### PR DESCRIPTION
**Pull request by FintanH**
Ensure that the deletion of cobs is respected by testing a scenario where a peer creates and then deletes an issue, while another peer fetches and also has the issue be present and then removed.

### CODE REVIEW

**Comment by cloudhead** [comment]
By the way I was thinking about this, and: if a peer deletes a COB that he hasn't interacted with, he shouldn't `sign-refs`, because there will be nothing new to sign, right?

**Comment by FintanH** [comment]
> By the way I was thinking about this, and: if a peer deletes a COB that he hasn't interacted with, he shouldn't `sign-refs`, because there will be nothing new to sign, right?

Ya, she wouldn't have any references to the COB, right?

**Comment by cloudhead** [comment]
Exactly, so somehow in the `delete` code, we should check before calling `sign_refs`, to not create a commit.

**Comment by FintanH** [comment]
> Exactly, so somehow in the `delete` code, we should check before calling `sign_refs`, to not create a commit.

Hmmm, I'm not sure I follow. Is this to avoid needlessly creating a new set of signed refs?

**Comment by cloudhead** [comment]
Yes exactly, it would be identical to the previous one.

**Comment by FintanH** [comment]
> Yes exactly, it would be identical to the previous one.

I guess the only thing is that it would come at the cost of loading the `sigrefs` first. Do you think that's worth it?

**Comment by cloudhead** [comment]
I'm not sure we'd need to load sigrefs. I think we can just check if a ref exists under the remote, for that cob.

**Comment by FintanH** [comment]
> I'm not sure we'd need to load sigrefs. I think we can just check if a ref exists under the remote, for that cob.

Ah ya that's fair. It should be equivalent

**Comment by cloudhead** [comment]
Hmm good question, is `cob::remove` actually a no-op if you don't have your own refs, or does it remove from all remotes? If the former, then we don't need to call it.

**Comment by FintanH** [comment]
> Hmm good question, is `cob::remove` actually a no-op if you don't have your own refs, or does it remove from all remotes? If the former, then we don't need to call it.

So it just deletes the reference, so it would make sense to not remove it if it doesn't exist :) I'll add that to the change as well

**Comment by FintanH** [comment]
Closing in favour of https://app.radicle.xyz/seeds/seed.radicle.xyz/rad:z3gqcJUoA1n9HaHKufZs5FCSGazv5/patches/553c795ab9a8b0a7c8e0dfec95568ba11c018ad2?tab=files

**Pull request closed without merging**
