### PR TITLE
radicle: simplify issue commenting

### PR DESCRIPTION
**Pull request by slack-coder**
Make commenting on an issue easier by offering a default option when 'reply_to' is None.  The default is set to the thread root comment `OpId(issue.author)`.

### CODE REVIEW

**Comment by cloudhead** [comment]
I don't get how this is an improvement..

**Comment by slack-coder** [comment]
I don't get how issue comments are supposed to work.  Can we try making them more intuitive?

When I am generally commenting on this issue on Github, I reply on the issue, not a comment.  Without this change it appears I need to find a comment (the root?) and guess the author for 'OpId:root()'.  Is this the correct interpretation?

**Comment by cloudhead** [comment]
I'm not sure if you're talking about the CRDT or the `IssueMut::comment` method, but all comments must have a parent (reply_to) except the root comment. If you want to post a top-level comment, you'd set `reply_to` to the root comment op-id.

**Comment by cloudhead** [comment]
Ok gotcha. The `OpId` should not be constructed manually. You should be able to get the root comment with `issue.root()`. It will return the OpId, then use that OpId as `reply_to`.

**Comment by cloudhead** [comment]
Closing this. If there's still a feeling that the API is not adequate, we can discuss potential changes in an issue maybe.

**Pull request closed without merging**
