### PR TITLE
Add ZSH completion script

### PR DESCRIPTION
**Pull request by adaszko**
In order to use it, the file needs to be copied to one of the directories residing in the `$fpath` zsh variable.  Is README the best place for that kind of instructions?

termtosvg_3z7fks9z

### CODE REVIEW

**Comment by vincenzopalazzo** [comment]
>Is README the best place for that kind of instructions?

It is not possible to do this under the hood while rad is bootstrapping? I use zsh but I never edited the `$fpath` or added content under it?

**Comment by adaszko** [comment]
>  I use zsh but I never edited the $fpath or added content under it?

How do you install custom zsh completions then (i.e. not those in the package manager)?

**Comment by vincenzopalazzo** [comment]
>How do you install custom zsh completions then (i.e. not those in the package manager)?

Maybe I do not have the full context but if you had the access to `$fpath` to can teach the `rad` command line to do this at the first run?

**Comment by adaszko** [comment]
> > How do you install custom zsh completions then (i.e. not those in the package manager)?
> 
> Maybe I do not have the full context but if you had the access to `$fpath` to can teach the `rad` command line to do this at the first run?

The way it’s often done is to append a snippet to user’s `.zshrc` but that doesn’t address uninstalling so a better way IMO is to use the package manager to manage it (Homebrew and alike).

**Comment by cloudhead** [comment]
I'm reluctant to merge this as it seems like it will be a maintenance nightmare. 

Perhaps as a first step, if we want something like this, we could just complete the sub-commands, eg. rad patch, rad issue, and not all of the flags?

**Comment by cloudhead** [comment]
Closing this for now. If you feel like making a minimal version of it as described, feel free to open directly on radicle.

**Comment by adaszko** [comment]
> Closing this for now. If you feel like making a minimal version of it as described, feel free to open directly on radicle.

👍

**Pull request closed without merging**
