### PR TITLE
node: fix inconsistently failing test

### PR DESCRIPTION
**Pull request by slack-coder**
Fix the test for pruning a node's inventory which inconsistently and rarely fails.  It fails due to each test peers' clocks being slightly out of sync in the test.  One peer may have their clock skewed one second before the other.

The test confirms how pruning inventory entries relates to time.  Time therefor needs to be accurate to test against internal edge cases.

Note:

I would prefer to sync the clocks manually, the alternative of using an 'if' and 'elapsed' combination seems a bit much.

i.e.
```
bob.clock().set(alice.clock().local_time());
```

### CODE REVIEW

**Comment by FintanH** [comment]
One question this prompts for me is whether this is just fixing the test rather than fixing the actual problem in the code? I'm not sure of the answer because I'm not sure I understand the issue :)

**Comment by slack-coder** [comment]
> One question this prompts for me is whether this is just fixing the test rather than fixing the actual problem in the code? I'm not sure of the answer because I'm not sure I understand the issue :)

The PR comment and commit message needed some tending to.  Is the new description clear?

**Comment by FintanH** [comment]
I _think_ so. I suppose another way of phrasing my question is, "Can this clock skew happen in practice? And is the failure correct in that case?"

**Comment by slack-coder** [comment]
The test is for confirming whether internal mechanisms work as expected using the public api.

**Review by FintanH — APPROVED** [review]

**Comment by slack-coder** [comment]
> I _think_ so. I suppose another way of phrasing my question is, "Can this clock skew happen in practice? And is the failure correct in that case?"

Thanks for the review :+1:.  It does feel off using one peer's timestamp for another's message.  I'll try addressing this in this PR.  Upcoming tests may run into the same issue, so it is good to address.

**Comment by slack-coder** [comment]
@FintanH I made some significant changes

**Review by cloudhead — APPROVED** [review]

**Comment by cloudhead** [comment]
Nice.

**Comment by FintanH** [comment]
Nice one :) Much better!

**Pull request merged**
